### ISSUE TITLE
Down Air: Vertical boost

### ISSUE THREAD

**Issue by ZeDespo** [ZeDespo/Ultimate-Ganondorf#8]
Like Fox's shine, should give a tiny bit of vertical velocity only once in the air. If the move is done while Ganondorf is floating, it does not count.

**Comment by FatherOfEgg** [comment]
Do you want it so that when you get hit, you get the ability to stall in the air again? Obviously when you land or grab ledge you get it back.

**Comment by ZeDespo** [comment]
That sounds awesome!
